### ISSUE TITLE
error: <403 Forbidden>

### ISSUE THREAD

**Issue by DarkC0der-0** [bn3t/udemy-dl-rs#2]
root@DarkRoot:~/Desktop/udemy-dl-rs# cargo run -- -u https://www.udemy.com/thermodynamics-for-engineering-students/ -t access.txt download
   Compiling udemy-dl-rs v0.9.3 (/root/Desktop/udemy-dl-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 4.46s
     Running `target/debug/udemy-dl-rs -u 'https://www.udemy.com/thermodynamics-for-engineering-students/' -t access.txt download`
An error Occured: Error while getting from url <https://www.udemy.com/api-2.0/users/me/subscribed-courses?fields[course]=id,url,published_title&page=1&page_size=1000&ordering=-access_time&search=thermodynamics-for-engineering-students>, error: <403 Forbidden>

**Comment by bn3t** [comment]
You have to use the access token as the -t parameter, not a file containing it. See https://github.com/bn3t/udemy-dl-rs#extracting-your-access-token.
